import numpy as np

def export_obj(vertices, faces, filename):
    with open(filename, 'w') as f:
        f.write(f"# Generated by mesh_generator.py\n")
        for v in vertices:
            f.write(f"v {v[0]:.4f} {v[1]:.4f} {v[2]:.4f}\n")
        for face in faces:
            # OBJ 索引从1开始
            f.write(f"f {face[0]+1} {face[1]+1} {face[2]+1}\n")
    print(f"Saved {filename}: {len(vertices)} vertices, {len(faces)} faces.")

# 生成平面
def create_plane(res_x=20, res_z=20, size=4.0):
    verts = []
    faces = []
    
    # 生成顶点
    dx = size / (res_x - 1)
    dz = size / (res_z - 1)
    
    for z in range(res_z):
        for x in range(res_x):
            px = -size/2 + x * dx
            pz = -size/2 + z * dz
            verts.append([px, 0, pz])
            
    # 生成面
    for z in range(res_z - 1):
        for x in range(res_x - 1):
            p1 = z * res_x + x
            p2 = p1 + 1
            p3 = (z + 1) * res_x + x
            p4 = p3 + 1
            
            faces.append([p1, p3, p2])
            faces.append([p2, p3, p4])
            
    export_obj(verts, faces, "plane.obj")

# 生成窗帘
def create_curtain(res_x=20, res_y=20, width=3.0, height=3.0):
    verts = []
    faces = []
    
    dx = width / (res_x - 1)
    dy = height / (res_y - 1)
    
    # 稍微加一点波浪，让它不那么平
    for y in range(res_y):
        for x in range(res_x):
            px = -width/2 + x * dx
            py = height - y * dy
            pz = np.sin(x * 0.5) * 0.1 
            verts.append([px, py, pz])
            
    for y in range(res_y - 1):
        for x in range(res_x - 1):
            p1 = y * res_x + x
            p2 = p1 + 1
            p3 = (y + 1) * res_x + x
            p4 = p3 + 1
            faces.append([p1, p3, p2])
            faces.append([p2, p3, p4])
            
    export_obj(verts, faces, "curtain_simple.obj")

if __name__ == "__main__":
    create_plane()
    #create_curtain()